set shell := ["bash", "-cu"]

venv:
    python3 -m venv venv
    . venv/bin/activate

install: venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r requirements.txt

freeze: install
    venv/bin/pip freeze > requirements.txt

setup: venv
    venv/bin/python3 -m modal setup

transcribe: venv
    venv/bin/modal run transcriber.py

clean:
    rm -rf venv __pycache__

# To deactivate virtual environment 
# run "deactivate"

serve: venv
    venv/bin/modal serve transcriber.py

deploy: venv
    venv/bin/modal deploy transcriber.py
