start:
    node --env-file .env index.js

test:
    curl -X POST http://localhost:8000/api/v1/transcripts/trigger \
    -H "Content-Type: application/json" \
    -d '{ \
    "audioUrl": "https://drive.google.com/file/d/0B9YPx2tdNz1mVnRBYWNKMjNUck0/view?usp=drivesdk&resourcekey=0-9zTOEwwBnOq87wai56o27g" \
    }'
