--
-- PostgreSQL database dump
--

--
-- Name: bookmark_categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookmark_categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    name character varying(50) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.bookmark_categories OWNER TO postgres;

--
-- Name: bookmark_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookmark_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmark_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookmarks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bookmarks (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    note character varying(500),
    category_id bigint NOT NULL,
    teaching_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.bookmarks OWNER TO postgres;

--
-- Name: bookmarks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bookmarks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookmarks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: collection_teachings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collection_teachings (
    collection_id bigint NOT NULL,
    teaching_id bigint NOT NULL
);


ALTER TABLE public.collection_teachings OWNER TO postgres;

--
-- Name: collections; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.collections (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    thumbnail_url character varying(100) NOT NULL
);


ALTER TABLE public.collections OWNER TO postgres;

--
-- Name: collections_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.collections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.collections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: histories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.histories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    is_marked_read boolean NOT NULL,
    teaching_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.histories OWNER TO postgres;

--
-- Name: histories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.histories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.series (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    name character varying(50) NOT NULL,
    thumbnail_url character varying(100) NOT NULL
);


ALTER TABLE public.series OWNER TO postgres;

--
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teachings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teachings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    audio_url character varying(100) NOT NULL,
    message text NOT NULL,
    scriptural_references character varying(255) NOT NULL,
    series_part integer,
    summary character varying(255) NOT NULL,
    tags character varying(255) NOT NULL,
    taught_at timestamp(6) without time zone NOT NULL,
    thumbnail_url character varying(100) NOT NULL,
    title character varying(50) NOT NULL,
    type character varying(255) NOT NULL,
    video_url character varying(100) NOT NULL,
    series_id bigint,
    transcript_id bigint,
    CONSTRAINT teachings_type_check CHECK (((type)::text = ANY ((ARRAY['SUNDAY_SERVICE'::character varying, 'EXTERNAL_MINISTRATION'::character varying, 'CONFERENCE'::character varying, 'SPECIAL_SERVICE'::character varying])::text[])))
);


ALTER TABLE public.teachings OWNER TO postgres;

--
-- Name: teachings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teachings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.test_table (
    id integer NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.test_table OWNER TO postgres;

--
-- Name: test_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.test_table_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.test_table_id_seq OWNER TO postgres;

--
-- Name: test_table_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.test_table_id_seq OWNED BY public.test_table.id;


--
-- Name: tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    is_used boolean DEFAULT false NOT NULL,
    type character varying(20) NOT NULL,
    value character varying(255) NOT NULL,
    version bigint,
    CONSTRAINT tokens_type_check CHECK (((type)::text = ANY ((ARRAY['VERIFY_EMAIL'::character varying, 'CHANGE_PASSWORD'::character varying, 'ACCESS_TOKEN'::character varying, 'REFRESH_TOKEN'::character varying])::text[])))
);


ALTER TABLE public.tokens OWNER TO postgres;

--
-- Name: tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transcripts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transcripts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    title character varying(50) NOT NULL
);


ALTER TABLE public.transcripts OWNER TO postgres;

--
-- Name: transcripts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transcripts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transcripts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    email character varying(100) NOT NULL,
    first_name character varying(50) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    last_name character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    photo_url character varying(100),
    role character varying(10) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_table id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_table ALTER COLUMN id SET DEFAULT nextval('public.test_table_id_seq'::regclass);


--
-- Name: bookmark_categories bookmark_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmark_categories
    ADD CONSTRAINT bookmark_categories_pkey PRIMARY KEY (id);


--
-- Name: bookmarks bookmarks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT bookmarks_pkey PRIMARY KEY (id);


--
-- Name: collections collections_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collections
    ADD CONSTRAINT collections_pkey PRIMARY KEY (id);


--
-- Name: histories histories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.histories
    ADD CONSTRAINT histories_pkey PRIMARY KEY (id);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: teachings teachings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT teachings_pkey PRIMARY KEY (id);


--
-- Name: test_table test_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.test_table
    ADD CONSTRAINT test_table_pkey PRIMARY KEY (id);


--
-- Name: tokens tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);


--
-- Name: transcripts transcripts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transcripts
    ADD CONSTRAINT transcripts_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: teachings uk7ommfx9qfe5rcx53c1soxl3x9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT uk7ommfx9qfe5rcx53c1soxl3x9 UNIQUE (video_url);


--
-- Name: teachings ukn1fegbwagimaklpeuydudrwnj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT ukn1fegbwagimaklpeuydudrwnj UNIQUE (transcript_id);


--
-- Name: teachings ukr8wphxgctcmsani311eyue6v9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT ukr8wphxgctcmsani311eyue6v9 UNIQUE (audio_url);


--
-- Name: bookmarks unique_user_category_teaching; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT unique_user_category_teaching UNIQUE (user_id, category_id, teaching_id);


--
-- Name: histories unique_user_teaching; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.histories
    ADD CONSTRAINT unique_user_teaching UNIQUE (user_id, teaching_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: bookmarks fk3rqu0jn6mt2748gjhykhqf768; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fk3rqu0jn6mt2748gjhykhqf768 FOREIGN KEY (teaching_id) REFERENCES public.teachings(id);


--
-- Name: histories fk8w9eva74w7t7xtf2opb33f8bq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.histories
    ADD CONSTRAINT fk8w9eva74w7t7xtf2opb33f8bq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: bookmarks fkadkvohi31hvgg1kr590mow069; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkadkvohi31hvgg1kr590mow069 FOREIGN KEY (category_id) REFERENCES public.bookmark_categories(id);


--
-- Name: teachings fkblft2r0wdvepaj1de90hldakk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT fkblft2r0wdvepaj1de90hldakk FOREIGN KEY (series_id) REFERENCES public.series(id);


--
-- Name: bookmarks fkdbsho2e05w5r13fkjqfjmge5f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmarks
    ADD CONSTRAINT fkdbsho2e05w5r13fkjqfjmge5f FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: teachings fkeftoiqj3k9leun4fj3qnjhwjj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teachings
    ADD CONSTRAINT fkeftoiqj3k9leun4fj3qnjhwjj FOREIGN KEY (transcript_id) REFERENCES public.transcripts(id);


--
-- Name: histories fkmcx6ub3acgvpvx512m0fcn463; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.histories
    ADD CONSTRAINT fkmcx6ub3acgvpvx512m0fcn463 FOREIGN KEY (teaching_id) REFERENCES public.teachings(id);


--
-- Name: collection_teachings fkne15rtvy8yt9wrh0jlvrbkcdh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collection_teachings
    ADD CONSTRAINT fkne15rtvy8yt9wrh0jlvrbkcdh FOREIGN KEY (teaching_id) REFERENCES public.teachings(id);


--
-- Name: collection_teachings fkq6dh6pn18x77e98l3m017ujp6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.collection_teachings
    ADD CONSTRAINT fkq6dh6pn18x77e98l3m017ujp6 FOREIGN KEY (collection_id) REFERENCES public.collections(id);


--
-- Name: bookmark_categories fkv0uq5qa63xsepd45qjk0rqix; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bookmark_categories
    ADD CONSTRAINT fkv0uq5qa63xsepd45qjk0rqix FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

