-- Koinonia Daily - Initial Database Schema
-- Version: 1
-- Description: Creates core tables for users, teachings, bookmarks, histories, and related entities

-- =====================================================
-- USERS TABLE
-- =====================================================
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    email VARCHAR(100) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    photo_url VARCHAR(100),
    role VARCHAR(10) NOT NULL,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

-- =====================================================
-- TRANSCRIPTS TABLE
-- =====================================================
CREATE TABLE transcripts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    message TEXT NOT NULL,
    title VARCHAR(50) NOT NULL
);

-- =====================================================
-- SERIES TABLE
-- =====================================================
CREATE TABLE series (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(100) NOT NULL
);

-- =====================================================
-- COLLECTIONS TABLE
-- =====================================================
CREATE TABLE collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(100) NOT NULL
);

-- =====================================================
-- TEACHINGS TABLE
-- =====================================================
CREATE TABLE teachings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    title VARCHAR(50) NOT NULL,
    scriptural_references VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    summary VARCHAR(255) NOT NULL,
    audio_url VARCHAR(100) NOT NULL,
    video_url VARCHAR(100) NOT NULL,
    thumbnail_url VARCHAR(100) NOT NULL,
    type VARCHAR(50) NOT NULL,
    tags VARCHAR(255) NOT NULL,
    series_part INTEGER,
    taught_at TIMESTAMPTZ NOT NULL,
    transcript_id BIGINT,
    series_id BIGINT,
    CONSTRAINT teachings_audio_url_unique UNIQUE (audio_url),
    CONSTRAINT teachings_video_url_unique UNIQUE (video_url),
    CONSTRAINT teachings_transcript_id_unique UNIQUE (transcript_id),
    CONSTRAINT teachings_type_check CHECK (type IN ('SUNDAY_SERVICE', 'EXTERNAL_MINISTRATION', 'CONFERENCE', 'SPECIAL_SERVICE')),
    CONSTRAINT teachings_transcript_fk FOREIGN KEY (transcript_id) REFERENCES transcripts(id),
    CONSTRAINT teachings_series_fk FOREIGN KEY (series_id) REFERENCES series(id)
);

-- =====================================================
-- COLLECTION_TEACHINGS JUNCTION TABLE
-- =====================================================
CREATE TABLE collection_teachings (
    collection_id BIGINT NOT NULL,
    teaching_id BIGINT NOT NULL,
    CONSTRAINT collection_teachings_collection_fk FOREIGN KEY (collection_id) REFERENCES collections(id),
    CONSTRAINT collection_teachings_teaching_fk FOREIGN KEY (teaching_id) REFERENCES teachings(id)
);

ALTER TABLE collection_teachings
    ADD CONSTRAINT collection_teachings_pk PRIMARY KEY (collection_id, teaching_id);

-- =====================================================
-- BOOKMARK_CATEGORIES TABLE
-- =====================================================
CREATE TABLE bookmark_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    name VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT bookmark_categories_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- BOOKMARKS TABLE
-- =====================================================
CREATE TABLE bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    note VARCHAR(500),
    category_id BIGINT NOT NULL,
    teaching_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT bookmarks_user_category_teaching_unique UNIQUE (user_id, category_id, teaching_id),
    CONSTRAINT bookmarks_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT bookmarks_category_fk FOREIGN KEY (category_id) REFERENCES bookmark_categories(id),
    CONSTRAINT bookmarks_teaching_fk FOREIGN KEY (teaching_id) REFERENCES teachings(id)
);

-- =====================================================
-- HISTORIES TABLE
-- =====================================================
CREATE TABLE histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    is_marked_read BOOLEAN NOT NULL,
    teaching_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT histories_user_teaching_unique UNIQUE (user_id, teaching_id),
    CONSTRAINT histories_user_fk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT histories_teaching_fk FOREIGN KEY (teaching_id) REFERENCES teachings(id)
);

-- =====================================================
-- TOKENS TABLE
-- =====================================================
CREATE TABLE tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    email VARCHAR(100) NOT NULL,
    value VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    is_used BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMPTZ NOT NULL,
    version BIGINT,
    CONSTRAINT tokens_type_check CHECK (type IN ('VERIFY_EMAIL', 'CHANGE_PASSWORD', 'ACCESS_TOKEN', 'REFRESH_TOKEN'))
);

-- =====================================================
-- INDEXES
-- =====================================================

-- User indexes
CREATE INDEX idx_users_email ON users(email);

-- Teaching indexes for common queries
CREATE INDEX idx_teachings_series_id ON teachings(series_id);
CREATE INDEX idx_teachings_transcript_id ON teachings(transcript_id);

-- Token indexes for lookup performance
CREATE INDEX idx_tokens_email_type_value ON tokens(email, type, value);

-- Bookmark category indexes
CREATE INDEX idx_bookmark_categories_user_id ON bookmark_categories(user_id);

-- Bookmark indexes
CREATE INDEX idx_bookmarks_user_id ON bookmarks(user_id);
CREATE INDEX idx_bookmarks_category_id ON bookmarks(category_id);
CREATE INDEX idx_bookmarks_teaching_id ON bookmarks(teaching_id);

-- History indexes
CREATE INDEX idx_histories_user_id ON histories(user_id);
CREATE INDEX idx_histories_teaching_id ON histories(teaching_id);

-- Collection junction table indexes
CREATE INDEX idx_collection_teachings_teaching_id ON collection_teachings(teaching_id);
