CREATE TABLE teaching_chunks (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_id       BIGINT NOT NULL REFERENCES teachings(id) ON DELETE CASCADE,

  -- Chunk content
  chunk_index       INT NOT NULL,-- Order within teaching
  content           TEXT NOT NULL,
  tsv               TSVECTOR,

  -- Metadata for search results display
  teaching_title    VARCHAR(60),
  section_title     VARCHAR(100),
  start_offset      INT,

  embedding_status  VARCHAR(20) DEFAULT 'PENDING',

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL,

  CONSTRAINT teaching_id_chunk_index_unique UNIQUE(teaching_id, chunk_index),
  CONSTRAINT teaching_chunks_embedding_status_check
      CHECK (embedding_status IN ('PENDING', 'PROCESSING', 'EMBEDDED', 'FAILED'))
);

CREATE INDEX idx_teaching_chunks_teaching_id ON teaching_chunks(teaching_id);

CREATE INDEX idx_teaching_chunks_tsv ON teaching_chunks USING GIN (tsv);

CREATE OR REPLACE FUNCTION chunk_tsv_trigger()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.tsv :=
        set_weight(to_tsvector('english', coalesce(NEW.teaching_title, '')), 'A') ||
        set_weight(to_tsvector('english', coalesce(NEW.section_title, '')), 'B') ||
        set_weight(to_tsvector('english', coalesce(NEW.content, '')), 'C');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER chunk_tsv_update
    BEFORE INSERT OR UPDATE ON teaching_chunks
    FOR EACH ROW
EXECUTE PROCEDURE chunk_tsv_trigger();