CREATE TABLE teaching_chunks (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_id       BIGINT NOT NULL REFERENCES teachings(id) ON DELETE CASCADE,

  -- Chunk content
  chunk_index       INT NOT NULL,-- Order within teaching
  content           TEXT NOT NULL,

  -- Metadata for search results display
  section_title     VARCHAR(100),
  startOffset       INT,

  embedding_status  VARCHAR(20) DEFAULT 'PENDING',

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL,

  CONSTRAINT teaching_id_chunk_index_unique UNIQUE(teaching_id, chunk_index),
  CONSTRAINT teaching_chunks_embedding_status_check
      CHECK (embedding_status IN ('PENDING', 'PROCESSING', 'EMBEDDED', 'FAILED'))
);

CREATE OR REPLACE FUNCTION chunk_tsv_trigger()
    RETURNS TRIGGER AS
$$
BEGIN
    NEW.tsv := to_tsvector('english', NEW.content);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER chunk_tsv_update
    BEFORE INSERT OR UPDATE ON teaching_chunks
    FOR EACH ROW
EXECUTE PROCEDURE chunk_tsv_trigger();

CREATE INDEX idx_teaching_chunks_teaching_id
  ON teaching_chunks(teaching_id);