CREATE TABLE chunk_embeddings (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_chunk_id BIGINT NOT NULL REFERENCES teaching_chunks(id) ON DELETE CASCADE,

  model             VARCHAR(100) NOT NULL,

  -- Vector embedding
  embedding         VECTOR(1536) NOT NULL,

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL,

  CONSTRAINT teaching_chunk_id_model_unique UNIQUE(teaching_chunk_id, model)
);

CREATE INDEX chunk_embeddings_embedding
  ON chunk_embeddings
  USING HNSW (embedding vector_cosine_ops);

CREATE INDEX idx_chunk_embeddings_teaching_chunk_id
  ON chunk_embeddings(teaching_chunk_id);