CREATE TABLE teaching_embeddings (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teaching_id BIGINT NOT NULL REFERENCES teachings(id) ON DELETE CASCADE,

  model             VARCHAR(100) NOT NULL,

  -- Vector embedding
  embedding         VECTOR(1536) NOT NULL,

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL,

  CONSTRAINT teaching_id_model_unique UNIQUE(teaching_id, model)
);

CREATE INDEX teaching_embeddings_embedding
  ON teaching_embeddings
  USING HNSW (embedding vector_cosine_ops);

CREATE INDEX idx_teaching_embeddings_teaching_id
  ON teaching_embeddings(teaching_id);