CREATE TABLE search_clicks (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id             BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  teaching_id       BIGINT NOT NULL REFERENCES teachings(id) ON DELETE CASCADE,

  -- Timestamps
  created_at        TIMESTAMPTZ NOT NULL,
  updated_at        TIMESTAMPTZ NOT NULL,

  CONSTRAINT search_clicks_user_teaching_unique UNIQUE(user_id, teaching_id)
);

CREATE INDEX idx_search_clicks_user_updated_at
  ON search_clicks(user_id, updated_at DESC);

CREATE INDEX idx_search_clicks_teaching_id
  ON search_clicks(teaching_id);