spring.application.name=Koinonia-Daily

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.profiles.include=local

logging.level.org.framework.boot.context.config=INFO

sentry.dsn=${SENTRY_DSN:}