spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.flyway.clean-disabled=true

logging.level.org.springframework.jdbc=DEBUG

sentry.enabled=false
sentry.send-default-pii=false
sentry.environment=development
sentry.logging.enabled=false
sentry.enable-tracing=false
sentry.logging.minimum-breadcrumb-level=info
sentry.logging.minimum-event-level=error

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

app.email.provider=mailtrap

app.embedding.queue.provider=local
app.embedding.model.provider=text-embedding-3-small

app.transcription.provider=modal

# -- Required via application-local.properties
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# app.seeder-user-password=
# app.base-url=
# app.jwt.secret=
# app.aws.access-key=
# app.aws.secret-key=
# app.aws.region=
# app.aws.s3-bucket-name=
# app.aws.sqs.queue-url=
# sentry.dsn=
# app.email.from=
# app.mailtrap.username=
# app.mailtrap.password=
# app.openai-api-key=
# app.transcription.modal.url=
# app.transcription.modal.api-key=
# app.transcription.modal.callback-secret=
