spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.flyway.clean-disabled=true

logging.level.org.springframework.jdbc=DEBUG

sentry.enabled=false
sentry.send-default-pii=false
sentry.environment=development
sentry.logging.enabled=false
sentry.enable-tracing=false
sentry.logging.minimum-breadcrumb-level=info
sentry.logging.minimum-event-level=error

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.info.env.enabled=true

app.email.provider=mailtrap

# -- Required via application-local.properties
# spring.datasource.url=
# spring.datasource.username=
# spring.datasource.password=
# app.seeder-user-password=
# app.jwt.secret=
# app.aws.access-key=
# app.aws.secret-key=
# app.aws.region=
# app.aws.s3-bucket-name=
# sentry.dsn=
# app.email.from=
# app.mailtrap.password=