spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.flyway.clean-disabled=true
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false

app.jwt-secret=${JWT_SECRET}

app.email.provider=${APP_EMAIL_PROVIDER}
app.email.from=${APP_EMAIL_FROM}
app.mailtrap.username=${APP_MAILTRAP_USERNAME}
app.mailtrap.password=${APP_MAILTRAP_PASSWORD}
app.aws.access-key=${AWS_ACCESS_KEY}
app.aws.secret-key=${AWS_SECRET_KEY}
app.aws.region=${AWS_REGION}
app.aws.s3-bucket-name=${AWS_S3_BUCKET_NAME}
app.embedding.queue.provider=${APP_EMBEDDING_QUEUE_PROVIDER}
app.embedding.model.provider=${APP_EMBEDDING_MODEL_PROVIDER}

app.openai-api-key=${OPENAI_API_KEY}

# Sentry settings for production
sentry.dsn=${SENTRY_DSN}
sentry.environment=production
sentry.send-default-pii=false
sentry.traces-sample-rate=0.1
sentry.logging.enabled=true
sentry.enable-tracing=true

sentry.max-breadcrumbs=100
sentry.max-cache-items=30
sentry.attach-stacktrace=true
sentry.attach-threads=false
sentry.logging.minimum-breadcrumb-level=info
sentry.logging.minimum-event-level=error

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never
management.info.env.enabled=false

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false