spring.application.name=Koinonia-Daily

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.profiles.include=local

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

logging.level.org.springframework.boot.context.config=INFO

app.mailtrap.host=live.smtp.mailtrap.io
app.mailtrap.port=587
app.mailtrap.username=api

sentry.dsn=${SENTRY_DSN:}