export const recentSearchesData = [
  {
    id: '1',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: true,
    tags: 'Counsel',
  },
  {
    id: '2',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: null,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '3',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: 2,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '4',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: false,
    tags: 'Redemption, Salvation',
  },
  {
    id: '5',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: 1,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '6',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '7',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: true,
    tags: 'Glory, Hunger',
  },
  {
    id: '8',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: false,
    tags: 'Redemption, Salvation',
  },
  {
    id: '9',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: 3,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '10',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '11',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Glory, Hunger',
  },
  {
    id: '12',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: true,
    tags: 'Counsel',
  },
  {
    id: '13',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: null,
    isNew: true,
    tags: 'Kingdom, Authority',
  },
  {
    id: '14',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '15',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: 1,
    isNew: false,
    tags: 'Glory, Hunger',
  },
  {
    id: '16',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: true,
    tags: 'Counsel',
  },
  {
    id: '17',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: null,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '18',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: 2,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '19',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: false,
    tags: 'Redemption, Salvation',
  },
  {
    id: '20',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: 1,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '21',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '22',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: true,
    tags: 'Glory, Hunger',
  },
  {
    id: '23',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: false,
    tags: 'Redemption, Salvation',
  },
  {
    id: '24',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: 3,
    isNew: false,
    tags: 'Kingdom, Authority',
  },
  {
    id: '25',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '26',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Glory, Hunger',
  },
  {
    id: '27',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
    taughtAt: 'April 7, 2023',
    seriesPart: null,
    isNew: true,
    tags: 'Counsel',
  },
  {
    id: '28',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
    taughtAt: 'Mar 6, 2025',
    seriesPart: null,
    isNew: true,
    tags: 'Kingdom, Authority',
  },
  {
    id: '29',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: null,
    isNew: false,
    tags: 'Spirit, Wisdom, Revelation',
  },
  {
    id: '30',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
    taughtAt: 'April 15, 2026',
    seriesPart: 1,
    isNew: false,
    tags: 'Glory, Hunger',
  },
];

export const teachings = recentSearchesData;

export const searchResultsData = [
  {
    id: '1',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
  {
    id: '2',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'EXACT',
  },
  {
    id: '3',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'TRANSCRIPT',
  },
  {
    id: '4',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
  {
    id: '5',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
  {
    id: '6',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'EXACT',
  },
  {
    id: '7',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'TRANSCRIPT',
  },
  {
    id: '8',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
  {
    id: '9',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
  {
    id: '10',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'EXACT',
  },
  {
    id: '11',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'TRANSCRIPT',
  },
  {
    id: '12',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    searchTag: 'SIMILAR',
  },
];

export const trendingTeachingsData = [
  {
    id: '1',
    title: 'Complete Deliverance: The Power of the Blood',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    taughtAt: 'April 7, 2023',
    viewCount: '2.4k',
  },
  {
    id: '2',
    title: 'The Sound of Revival: An Awakening to True Spirituality',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'CONFERENCE' as const,
    taughtAt: 'Mar 6, 2025',
    viewCount: '2.3k',
  },
  {
    id: '3',
    title: 'Making your Life Count',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    taughtAt: 'April 15, 2026',
    viewCount: '2.2k',
  },
];

export const discoveryTeachingsData = [
  {
    id: '1',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
  },
  {
    id: '2',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '3',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
  },
  {
    id: '4',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL_MINISTRATION' as const,
    createdAt: 'April 7, 2023',
  },
  {
    id: '5',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY_SERVICE' as const,
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '6',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
  },
  {
    id: '7',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE' as const,
    createdAt: 'April 15, 2026',
  },
];
