export const recentSearchesData = [
  {
    id: '1',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '2',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '3',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '4',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '5',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '6',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '7',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '8',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '9',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '10',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '11',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '12',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '13',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '14',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '15',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
];

export const searchResultsData = [
  {
    id: '1',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    searchTag: 'SIMILAR',
  },
  {
    id: '2',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    searchTag: 'EXACT',
  },
  {
    id: '3',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    searchTag: 'TRANSCRIPT',
  },
  {
    id: '4',
    title: 'Examining the Realities of our Redemption in Christ Jesus',
    text: 'Examining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ JesusExamining the Realities of our Redemption in Christ Jesus',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    searchTag: 'SIMILAR',
  },
];

export const trendingTeachingsData = [
  {
    id: '1',
    title: 'Complete Deliverance: The Power of the Blood',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'SUNDAY SERVICE',
    taughtAt: 'April 7, 2023',
    viewCount: '2.4k',
  },
  {
    id: '2',
    title: 'The Sound of Revival: An Awakening to True Spirituality',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'CONFERENCE',
    taughtAt: 'Mar 6, 2025',
    viewCount: '2.3k',
  },
  {
    id: '3',
    title: 'Making your Life Count',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'EXTERNAL MINISTRATION',
    taughtAt: 'April 15, 2026',
    viewCount: '2.2k',
  },
];

export const discoveryTeachingsData = [
  {
    id: '1',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '2',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '3',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '4',
    title: 'Walking in the Counsel of God',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'EXTERNAL MINISTRATION',
    createdAt: 'April 7, 2023',
  },
  {
    id: '5',
    title: 'Foundations of Kingdom Authority',
    thumbnailUrl: require('@/assets/images/p3.jpg'),
    type: 'SUNDAY SERVICE',
    createdAt: 'Mar 6, 2025',
  },
  {
    id: '6',
    title: 'The Spirit of Wisdom and Revelation',
    thumbnailUrl: require('@/assets/images/p1.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
  {
    id: '7',
    title: 'Ever Increasing Glory: A Desperate Cry for Hunger',
    thumbnailUrl: require('@/assets/images/p2.jpg'),
    type: 'CONFERENCE',
    createdAt: 'April 15, 2026',
  },
];
