services:
  app:
    build:
      context: .
      target: runtime

    container_name: koinonia-daily-server

    ports:
      - "8080:8080"

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - APP_EMAIL_PROVIDER=${APP_EMAIL_PROVIDER}
      - APP_EMAIL_FROM=${APP_EMAIL_FROM}
      - APP_MAILTRAP_USERNAME=${APP_MAILTRAP_USERNAME}
      - APP_MAILTRAP_PASSWORD=${APP_MAILTRAP_PASSWORD}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_SQS_QUEUE_URL=${AWS_SQS_QUEUE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_EMBEDDING_QUEUE_PROVIDER=${APP_EMBEDDING_QUEUE_PROVIDER}
      - APP_EMBEDDING_MODEL_PROVIDER=${APP_EMBEDDING_MODEL_PROVIDER}
      - APP_TRANSCRIPTION_PROVIDER=${APP_TRANSCRIPTION_PROVIDER}
      - APP_TRANSCRIPTION_MODAL_URL=${APP_TRANSCRIPTION_MODAL_URL}
      - APP_TRANSCRIPTION_MODAL_API_KEY=${APP_TRANSCRIPTION_MODAL_API_KEY}
      - APP_TRANSCRIPTION_MODAL_CALLBACK_SECRET=${APP_TRANSCRIPTION_MODAL_CALLBACK_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - SEEDER_USER_PASSWORD=${SEEDER_USER_PASSWORD}

    restart: unless-stopped