set shell := ["bash", "-cu"]

venv:
    python3 -m venv venv && \
    . venv/bin/activate

install: venv
    pip install --upgrade pip && \
    pip install -r requirements.txt

freeze: venv
    pip freeze > requirements.txt

transcribe: venv
    python transcriber.py

clean:
    rm -rf venv __pycache__

deactivate:
    . deactivate
