set shell := ["bash", "-cu"]

venv:
    python3 -m venv venv
    . venv/bin/activate

install: venv
    venv/bin/pip install --upgrade pip
    venv/bin/pip install -r requirements.txt

freeze: venv
    venv/bin/pip freeze > requirements.txt

transcribe: venv
    venv/bin/python transcriber.py

clean:
    rm -rf venv __pycache__

# To deactivate virtual environment 
# run "deactivate"
